version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://bot:password@db:5432/telegram_bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - kaktus-network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kaktus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot -d telegram_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  kaktus-network:
    driver: bridge